### ISSUE TITLE
Compiling The Game

### ISSUE THREAD

**Issue by Mapstabeats2** [ShadowMario/FNF-PsychEngine#15397]
### Describe your bug here.

An error pops up when i try to compile the game, SScript said bay bay now and idk what to do.

### Command Prompt/Terminal logs (if existing)

```bash
![image](https://github.com/user-attachments/assets/c6be1250-6803-4975-be0b-62a1a1753b9e)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing that could be come in contact with SScript.

**Comment by crowplexus** [comment]
fixed, use experimental branch https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental

**Comment by Mapstabeats2** [comment]
It still doesnt work for me : Getting this Error: C:/Users/napst/Desktop/Project/flixel/flxanimate/git/flxanimate/animate/FlxElement.hx:156: characters 39-40 : Unexpected ?

**Comment by crowplexus** [comment]
update haxe to version 4.3, you're using 4.2.5
