### ISSUE TITLE
Death Screen

### ISSUE THREAD

**Issue by KyleOliverDeveloper** [ShadowMario/FNF-PsychEngine#5132]
### Describe your bug here.

My Death animation wont work. Instead of the death screen being normal, it glitches to a bit of the spritesheet's sprites as seen in the image
![image](https://user-images.githubusercontent.com/94708825/154301153-76ed3bc7-d38d-48ed-acd6-48092df77170.png)
I need help, as if i cant find a way to fix it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited the mod's list, week, week bg assets, bgs, characters, chart, songs.

**Comment by frantastic24** [comment]
> ### Describe your bug here.

You missed the part where you describe the bug

**Comment by KyleOliverDeveloper** [comment]
> > ### Describe your bug here.
> 
> You missed the part where you describe the bug

the death animations dont work. Thats the bug

**Comment by frantastic24** [comment]
You posted a screenshot and that's it, didn't provide info at all
This report is unhelpful

**Comment by KyleOliverDeveloper** [comment]
> You posted a screenshot and that's it, didn't provide info at all This report is unhelpful

because its the only thing that happened

**Comment by KyleOliverDeveloper** [comment]
> You have no idea how a bug report works do you

i do have an idea of what it is, stop complaining for a mistake i made of not explaining

**Comment by KyleOliverDeveloper** [comment]
done, now its explaining

**Comment by frantastic24** [comment]
You explained the obvious, which still doesn't help 
It looks like the XML is wrong, but since there is still no information here are a few questions:
- does the sprite display properly in the character editor
- is this specific to this character/animation
- have you tried in another engine version

**Comment by KyleOliverDeveloper** [comment]
> You explained the obvious, which still doesn't help It looks like the XML is wrong, but since there is still no information here are a few questions:
> 
> * does the sprite display properly in the character editor
> * is this specific to this character/animation
> * have you tried in another engine version

Yes, the sprites do display in the character editor.
Yes it is.
No since im too lazy to download things rn

**Comment by frantastic24** [comment]
Do you mind sending me the character files so I can test it out?

**Comment by KyleOliverDeveloper** [comment]
> Do you mind sending me the character files so I can test it out?

ok
![arm](https://user-images.githubusercontent.com/94708825/154333097-f3c7d5cc-9de2-4065-a484-51fe22ec8fe8.png)


<?xml version="1.0" encoding="UTF-8"?>

-<TextureAtlas imagePath="arm.png">







<SubTexture frameHeight="378" frameWidth="852" frameY="-75" frameX="0" pivotY="-33" pivotX="28" height="303" width="852" y="0" x="0" name="ALT ARM DANCE DOWN0000"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="-75" frameX="0" height="303" width="852" y="0" x="0" name="ALT ARM DANCE DOWN0001"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="-24" frameX="-28" height="319" width="796" y="0" x="852" name="ALT ARM DANCE DOWN0002"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="-24" frameX="-28" height="319" width="796" y="0" x="852" name="ALT ARM DANCE DOWN0003"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="-11" frameX="-28" height="302" width="796" y="0" x="1648" name="ALT ARM DANCE DOWN0004"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="-11" frameX="-28" height="302" width="796" y="0" x="1648" name="ALT ARM DANCE DOWN0005"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="0" frameX="-28" height="318" width="796" y="0" x="2444" name="ALT ARM DANCE DOWN0006"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="0" frameX="-28" height="318" width="796" y="0" x="2444" name="ALT ARM DANCE DOWN0007"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="0" frameX="-28" height="318" width="796" y="0" x="2444" name="ALT ARM DANCE DOWN0008"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="0" frameX="-28" height="318" width="796" y="0" x="2444" name="ALT ARM DANCE DOWN0009"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="0" frameX="-28" height="318" width="796" y="0" x="2444" name="ALT ARM DANCE DOWN0010"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="0" frameX="-28" height="318" width="796" y="0" x="2444" name="ALT ARM DANCE DOWN0011"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="0" frameX="-28" height="318" width="796" y="0" x="2444" name="ALT ARM DANCE DOWN0012"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="0" frameX="-28" height="318" width="796" y="0" x="2444" name="ALT ARM DANCE DOWN0013"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="0" frameX="-28" height="318" width="796" y="0" x="2444" name="ALT ARM DANCE DOWN0014"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="0" pivotY="-6.6" pivotX="35.05" height="371" width="802" y="0" x="3240" name="ALT ARM DANCE LEFT0000"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="0" height="371" width="802" y="0" x="3240" name="ALT ARM DANCE LEFT0001"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-10" height="371" width="802" y="0" x="3240" name="ALT ARM DANCE LEFT0002"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-10" height="371" width="802" y="0" x="3240" name="ALT ARM DANCE LEFT0003"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-24" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0004"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-24" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0005"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-39" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0006"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-39" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0007"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-39" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0008"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-39" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0009"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-39" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0010"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-39" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0011"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-39" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0012"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-39" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0013"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-39" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0014"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="-63" pivotY="-21" pivotX="6.05" height="409" width="799" y="0" x="4844" name="ALT ARM DANCE RIGHT0000"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="-63" height="409" width="799" y="0" x="4844" name="ALT ARM DANCE RIGHT0001"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="-31" height="409" width="799" y="0" x="4844" name="ALT ARM DANCE RIGHT0002"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="-31" height="409" width="799" y="0" x="4844" name="ALT ARM DANCE RIGHT0003"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="-19" height="409" width="799" y="0" x="4844" name="ALT ARM DANCE RIGHT0004"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="-19" height="409" width="799" y="0" x="4844" name="ALT ARM DANCE RIGHT0005"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="0" height="409" width="798" y="0" x="5643" name="ALT ARM DANCE RIGHT0006"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="0" height="409" width="798" y="0" x="5643" name="ALT ARM DANCE RIGHT0007"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="0" height="409" width="798" y="0" x="5643" name="ALT ARM DANCE RIGHT0008"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="0" height="409" width="798" y="0" x="5643" name="ALT ARM DANCE RIGHT0009"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="0" height="409" width="798" y="0" x="5643" name="ALT ARM DANCE RIGHT0010"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="0" height="409" width="798" y="0" x="5643" name="ALT ARM DANCE RIGHT0011"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="0" height="409" width="798" y="0" x="5643" name="ALT ARM DANCE RIGHT0012"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="0" height="409" width="798" y="0" x="5643" name="ALT ARM DANCE RIGHT0013"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="0" height="409" width="798" y="0" x="5643" name="ALT ARM DANCE RIGHT0014"/>

<SubTexture pivotY="54.8" pivotX="16" height="429" width="828" y="0" x="6441" name="ALT ARM DANCE UP0000"/>

<SubTexture height="429" width="828" y="0" x="6441" name="ALT ARM DANCE UP0001"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-23" frameX="-9" height="389" width="811" y="0" x="7269" name="ALT ARM DANCE UP0002"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-23" frameX="-9" height="389" width="811" y="0" x="7269" name="ALT ARM DANCE UP0003"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-28" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0004"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-28" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0005"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-35" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0006"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-35" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0007"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-35" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0008"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-35" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0009"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-35" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0010"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-35" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0011"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-35" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0012"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-35" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0013"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-35" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0014"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="-51" frameX="0" pivotY="120" pivotX="-76.4" height="549" width="730" y="429" x="796" name="ARM DANCE DOWN0000"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="-51" frameX="0" height="549" width="730" y="429" x="796" name="ARM DANCE DOWN0001"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="-29" frameX="-8" height="552" width="710" y="429" x="1526" name="ARM DANCE DOWN0002"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="-29" frameX="-8" height="552" width="710" y="429" x="1526" name="ARM DANCE DOWN0003"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="-4" frameX="-8" height="563" width="710" y="429" x="2236" name="ARM DANCE DOWN0004"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="-4" frameX="-8" height="563" width="710" y="429" x="2236" name="ARM DANCE DOWN0005"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="0" frameX="-8" height="698" width="710" y="429" x="2946" name="ARM DANCE DOWN0006"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="0" frameX="-8" height="698" width="710" y="429" x="2946" name="ARM DANCE DOWN0007"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="0" frameX="-8" height="698" width="710" y="429" x="2946" name="ARM DANCE DOWN0008"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="0" frameX="-8" height="698" width="710" y="429" x="2946" name="ARM DANCE DOWN0009"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="0" frameX="-8" height="698" width="710" y="429" x="2946" name="ARM DANCE DOWN0010"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="0" frameX="-8" height="698" width="710" y="429" x="2946" name="ARM DANCE DOWN0011"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="0" frameX="-8" height="698" width="710" y="429" x="2946" name="ARM DANCE DOWN0012"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="0" frameX="-8" height="698" width="710" y="429" x="2946" name="ARM DANCE DOWN0013"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="0" frameX="-8" height="698" width="710" y="429" x="2946" name="ARM DANCE DOWN0014"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="-78" frameX="0" pivotY="0" pivotX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0000"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="-78" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0001"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="-44" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0002"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="-44" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0003"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="-26" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0004"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="-26" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0005"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="-16" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0006"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="-16" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0007"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="0" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0008"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="0" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0009"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="0" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0010"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="0" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0011"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="0" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0012"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="0" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0013"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="0" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0014"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="-65" frameX="-58" pivotY="260.7" pivotX="42.95" height="444" width="729" y="429" x="4452" name="ARM DANCE LEFT0000"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="-65" frameX="-58" height="444" width="729" y="429" x="4452" name="ARM DANCE LEFT0001"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="-34" frameX="-34" height="472" width="706" y="429" x="5181" name="ARM DANCE LEFT0002"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="-34" frameX="-34" height="472" width="706" y="429" x="5181" name="ARM DANCE LEFT0003"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="-16" frameX="-15" height="491" width="688" y="429" x="5887" name="ARM DANCE LEFT0004"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="-16" frameX="-15" height="491" width="688" y="429" x="5887" name="ARM DANCE LEFT0005"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="0" frameX="0" height="806" width="668" y="429" x="6575" name="ARM DANCE LEFT0006"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="0" frameX="0" height="806" width="668" y="429" x="6575" name="ARM DANCE LEFT0007"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="0" frameX="0" height="806" width="668" y="429" x="6575" name="ARM DANCE LEFT0008"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="0" frameX="0" height="806" width="668" y="429" x="6575" name="ARM DANCE LEFT0009"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="0" frameX="0" height="806" width="668" y="429" x="6575" name="ARM DANCE LEFT0010"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="0" frameX="0" height="806" width="668" y="429" x="6575" name="ARM DANCE LEFT0011"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="0" frameX="0" height="806" width="668" y="429" x="6575" name="ARM DANCE LEFT0012"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="0" frameX="0" height="806" width="668" y="429" x="6575" name="ARM DANCE LEFT0013"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="0" frameX="0" height="806" width="668" y="429" x="6575" name="ARM DANCE LEFT0014"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="-48" frameX="0" pivotY="272" pivotX="-84.2" height="489" width="761" y="429" x="7243" name="ARM DANCE RIGHT 0000"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="-48" frameX="0" height="489" width="761" y="429" x="7243" name="ARM DANCE RIGHT 0001"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="-27" frameX="-21" height="506" width="750" y="1235" x="0" name="ARM DANCE RIGHT 0002"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="-27" frameX="-21" height="506" width="750" y="1235" x="0" name="ARM DANCE RIGHT 0003"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="-15" frameX="-34" height="516" width="743" y="1235" x="750" name="ARM DANCE RIGHT 0004"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="-15" frameX="-34" height="516" width="743" y="1235" x="750" name="ARM DANCE RIGHT 0005"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="0" frameX="-50" height="813" width="735" y="1235" x="1493" name="ARM DANCE RIGHT 0006"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="0" frameX="-50" height="813" width="735" y="1235" x="1493" name="ARM DANCE RIGHT 0007"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="0" frameX="-50" height="813" width="735" y="1235" x="1493" name="ARM DANCE RIGHT 0008"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="0" frameX="-50" height="813" width="735" y="1235" x="1493" name="ARM DANCE RIGHT 0009"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="0" frameX="-50" height="813" width="735" y="1235" x="1493" name="ARM DANCE RIGHT 0010"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="0" frameX="-50" height="813" width="735" y="1235" x="1493" name="ARM DANCE RIGHT 0011"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="0" frameX="-50" height="813" width="735" y="1235" x="1493" name="ARM DANCE RIGHT 0012"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="0" frameX="-50" height="813" width="735" y="1235" x="1493" name="ARM DANCE RIGHT 0013"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="0" frameX="-50" height="813" width="735" y="1235" x="1493" name="ARM DANCE RIGHT 0014"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="-48" frameX="0" pivotY="149.1" pivotX="-66" height="671" width="681" y="1235" x="2228" name="ARM DANCE UP0000"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="-48" frameX="0" height="671" width="681" y="1235" x="2228" name="ARM DANCE UP0001"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="-23" frameX="-12" height="497" width="650" y="1235" x="2909" name="ARM DANCE UP0002"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="-23" frameX="-12" height="497" width="650" y="1235" x="2909" name="ARM DANCE UP0003"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="-6" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0004"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="-6" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0005"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="0" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0006"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="0" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0007"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="0" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0008"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="0" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0009"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="0" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0010"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="0" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0011"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="0" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0012"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="0" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0013"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="0" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0014"/>

<SubTexture frameHeight="1054" frameWidth="2572" frameY="0" frameX="0" pivotY="0" pivotX="0.35" height="996" width="2561" y="1235" x="4206" name="DEATH LOOP0000"/>

<SubTexture frameHeight="1054" frameWidth="2572" frameY="0" frameX="0" height="996" width="2561" y="1235" x="4206" name="DEATH LOOP0001"/>

<SubTexture frameHeight="1054" frameWidth="2572" frameY="-4" frameX="0" height="1012" width="2572" y="2231" x="0" name="DEATH LOOP0002"/>

<SubTexture frameHeight="1054" frameWidth="2572" frameY="-4" frameX="0" height="1012" width="2572" y="2231" x="0" name="DEATH LOOP0003"/>

<SubTexture frameHeight="1054" frameWidth="2572" frameY="-7" frameX="-18" height="1047" width="2546" y="2231" x="2572" name="DEATH LOOP0004"/>

<SubTexture frameHeight="1054" frameWidth="2572" frameY="-7" frameX="-18" height="1047" width="2546" y="2231" x="2572" name="DEATH LOOP0005"/>

<SubTexture frameHeight="1054" frameWidth="2572" frameY="-3" frameX="-6" height="1009" width="2565" y="2231" x="5118" name="DEATH LOOP0006"/>

<SubTexture frameHeight="1054" frameWidth="2572" frameY="-3" frameX="-6" height="1009" width="2565" y="2231" x="5118" name="DEATH LOOP0007"/>

<SubTexture frameHeight="947" frameWidth="2587" frameY="0" frameX="0" pivotY="0" pivotX="0" height="0" width="0" y="2231" x="7683" name="DIES0000"/>

<SubTexture frameHeight="947" frameWidth="2587" frameY="0" frameX="0" height="0" width="0" y="2231" x="7683" name="DIES0001"/>

<SubTexture height="947" width="2587" y="3278" x="0" name="DIES0002"/>

<SubTexture height="947" width="2587" y="3278" x="0" name="DIES0003"/>

<SubTexture height="947" width="2587" y="3278" x="2587" name="DIES0004"/>

<SubTexture height="947" width="2587" y="3278" x="2587" name="DIES0005"/>

<SubTexture height="947" width="2587" y="3278" x="5174" name="DIES0006"/>

<SubTexture height="947" width="2587" y="3278" x="5174" name="DIES0007"/>

<SubTexture height="947" width="2587" y="4225" x="0" name="DIES0008"/>

<SubTexture height="947" width="2587" y="4225" x="0" name="DIES0009"/>

<SubTexture height="947" width="2587" y="4225" x="2587" name="DIES0010"/>

<SubTexture height="947" width="2587" y="4225" x="2587" name="DIES0011"/>

<SubTexture height="947" width="2587" y="4225" x="2587" name="DIES0012"/>

<SubTexture height="947" width="2587" y="4225" x="2587" name="DIES0013"/>

<SubTexture height="947" width="2587" y="4225" x="2587" name="DIES0014"/>

<SubTexture pivotY="0" pivotX="0" height="692" width="611" y="4225" x="5174" name="REVIVE LMFAO0000"/>

<SubTexture height="692" width="611" y="4225" x="5174" name="REVIVE LMFAO0001"/>

<SubTexture height="692" width="611" y="4225" x="5174" name="REVIVE LMFAO0002"/>

<SubTexture height="692" width="611" y="4225" x="5174" name="REVIVE LMFAO0003"/>

<SubTexture height="692" width="611" y="4225" x="5785" name="REVIVE LMFAO0004"/>

<SubTexture height="692" width="611" y="4225" x="5785" name="REVIVE LMFAO0005"/>

<SubTexture frameHeight="692" frameWidth="611" frameY="0" frameX="0" height="0" width="0" y="4225" x="6396" name="REVIVE LMFAO0006"/>

<SubTexture frameHeight="692" frameWidth="611" frameY="0" frameX="0" height="0" width="0" y="4225" x="6396" name="REVIVE LMFAO0007"/>

<SubTexture frameHeight="692" frameWidth="611" frameY="0" frameX="0" height="0" width="0" y="4225" x="6396" name="REVIVE LMFAO0008"/>

<SubTexture frameHeight="692" frameWidth="611" frameY="0" frameX="0" height="0" width="0" y="4225" x="6396" name="REVIVE LMFAO0009"/>

<SubTexture frameHeight="692" frameWidth="611" frameY="0" frameX="0" height="0" width="0" y="4225" x="6396" name="REVIVE LMFAO0010"/>

<SubTexture frameHeight="692" frameWidth="611" frameY="0" frameX="0" height="0" width="0" y="4225" x="6396" name="REVIVE LMFAO0011"/>

</TextureAtlas>


{
	"animations": [
		{
			"offsets": [
				-216,
				21
			],
			"loop": false,
			"fps": 24,
			"anim": "singLEFT",
			"indices": [],
			"name": "ARM DANCE RIGHT"
		},
		{
			"offsets": [
				-111,
				52
			],
			"loop": false,
			"fps": 24,
			"anim": "singRIGHT",
			"indices": [],
			"name": "ARM DANCE LEFT"
		},
		{
			"offsets": [
				-123,
				0
			],
			"loop": false,
			"fps": 24,
			"anim": "singDOWN",
			"indices": [],
			"name": "ARM DANCE DOWN"
		},
		{
			"offsets": [
				-130,
				-17
			],
			"loop": false,
			"anim": "singUP",
			"fps": 24,
			"name": "ARM DANCE UP",
			"indices": []
		},
		{
			"loop": false,
			"offsets": [
				-134,
				-196
			],
			"anim": "idle",
			"fps": 24,
			"name": "ARM DANCE IDLE",
			"indices": []
		},
		{
			"offsets": [
				-96,
				-200
			],
			"loop": false,
			"fps": 24,
			"anim": "singLEFT-alt",
			"indices": [],
			"name": "ALT ARM DANCE LEFT"
		},
		{
			"offsets": [
				-111,
				-198
			],
			"loop": false,
			"fps": 24,
			"anim": "singRIGHT-alt",
			"indices": [],
			"name": "ALT ARM DANCE RIGHT"
		},
		{
			"offsets": [
				-123,
				-230
			],
			"loop": false,
			"fps": 24,
			"anim": "singDOWN-alt",
			"indices": [],
			"name": "ALT ARM DANCE DOWN"
		},
		{
			"offsets": [
				-130,
				-165
			],
			"loop": false,
			"fps": 24,
			"anim": "singUP-alt",
			"indices": [],
			"name": "ALT ARM DANCE UP"
		},
		{
			"offsets": [
				1664,
				120
			],
			"loop": true,
			"fps": 24,
			"anim": "deathLoop",
			"indices": [],
			"name": "DEATH LOOP"
		},
		{
			"offsets": [
				-310,
				40
			],
			"indices": [],
			"fps": 24,
			"anim": "deathConfirm",
			"loop": false,
			"name": "REVIVE LMFAO"
		},
		{
			"offsets": [
				1684,
				60
			],
			"indices": [],
			"fps": 24,
			"anim": "firstDeath",
			"loop": false,
			"name": "DIES"
		}
	],
	"no_antialiasing": false,
	"image": "characters/arm",
	"position": [
		-550,
		1260
	],
	"healthicon": "arm",
	"flip_x": true,
	"healthbar_colors": [
		170,
		171,
		158
	],
	"camera_position": [
		-250,
		120
	],
	"sing_duration": 4,
	"scale": 1
}

**Comment by KyleOliverDeveloper** [comment]
.XML:

<?xml version="1.0" encoding="UTF-8"?>

-<TextureAtlas imagePath="arm.png">







<SubTexture frameHeight="378" frameWidth="852" frameY="-75" frameX="0" pivotY="-33" pivotX="28" height="303" width="852" y="0" x="0" name="ALT ARM DANCE DOWN0000"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="-75" frameX="0" height="303" width="852" y="0" x="0" name="ALT ARM DANCE DOWN0001"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="-24" frameX="-28" height="319" width="796" y="0" x="852" name="ALT ARM DANCE DOWN0002"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="-24" frameX="-28" height="319" width="796" y="0" x="852" name="ALT ARM DANCE DOWN0003"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="-11" frameX="-28" height="302" width="796" y="0" x="1648" name="ALT ARM DANCE DOWN0004"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="-11" frameX="-28" height="302" width="796" y="0" x="1648" name="ALT ARM DANCE DOWN0005"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="0" frameX="-28" height="318" width="796" y="0" x="2444" name="ALT ARM DANCE DOWN0006"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="0" frameX="-28" height="318" width="796" y="0" x="2444" name="ALT ARM DANCE DOWN0007"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="0" frameX="-28" height="318" width="796" y="0" x="2444" name="ALT ARM DANCE DOWN0008"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="0" frameX="-28" height="318" width="796" y="0" x="2444" name="ALT ARM DANCE DOWN0009"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="0" frameX="-28" height="318" width="796" y="0" x="2444" name="ALT ARM DANCE DOWN0010"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="0" frameX="-28" height="318" width="796" y="0" x="2444" name="ALT ARM DANCE DOWN0011"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="0" frameX="-28" height="318" width="796" y="0" x="2444" name="ALT ARM DANCE DOWN0012"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="0" frameX="-28" height="318" width="796" y="0" x="2444" name="ALT ARM DANCE DOWN0013"/>

<SubTexture frameHeight="378" frameWidth="852" frameY="0" frameX="-28" height="318" width="796" y="0" x="2444" name="ALT ARM DANCE DOWN0014"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="0" pivotY="-6.6" pivotX="35.05" height="371" width="802" y="0" x="3240" name="ALT ARM DANCE LEFT0000"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="0" height="371" width="802" y="0" x="3240" name="ALT ARM DANCE LEFT0001"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-10" height="371" width="802" y="0" x="3240" name="ALT ARM DANCE LEFT0002"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-10" height="371" width="802" y="0" x="3240" name="ALT ARM DANCE LEFT0003"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-24" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0004"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-24" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0005"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-39" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0006"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-39" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0007"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-39" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0008"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-39" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0009"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-39" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0010"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-39" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0011"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-39" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0012"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-39" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0013"/>

<SubTexture frameHeight="371" frameWidth="842" frameY="0" frameX="-39" height="371" width="802" y="0" x="4042" name="ALT ARM DANCE LEFT0014"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="-63" pivotY="-21" pivotX="6.05" height="409" width="799" y="0" x="4844" name="ALT ARM DANCE RIGHT0000"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="-63" height="409" width="799" y="0" x="4844" name="ALT ARM DANCE RIGHT0001"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="-31" height="409" width="799" y="0" x="4844" name="ALT ARM DANCE RIGHT0002"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="-31" height="409" width="799" y="0" x="4844" name="ALT ARM DANCE RIGHT0003"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="-19" height="409" width="799" y="0" x="4844" name="ALT ARM DANCE RIGHT0004"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="-19" height="409" width="799" y="0" x="4844" name="ALT ARM DANCE RIGHT0005"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="0" height="409" width="798" y="0" x="5643" name="ALT ARM DANCE RIGHT0006"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="0" height="409" width="798" y="0" x="5643" name="ALT ARM DANCE RIGHT0007"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="0" height="409" width="798" y="0" x="5643" name="ALT ARM DANCE RIGHT0008"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="0" height="409" width="798" y="0" x="5643" name="ALT ARM DANCE RIGHT0009"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="0" height="409" width="798" y="0" x="5643" name="ALT ARM DANCE RIGHT0010"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="0" height="409" width="798" y="0" x="5643" name="ALT ARM DANCE RIGHT0011"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="0" height="409" width="798" y="0" x="5643" name="ALT ARM DANCE RIGHT0012"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="0" height="409" width="798" y="0" x="5643" name="ALT ARM DANCE RIGHT0013"/>

<SubTexture frameHeight="409" frameWidth="862" frameY="0" frameX="0" height="409" width="798" y="0" x="5643" name="ALT ARM DANCE RIGHT0014"/>

<SubTexture pivotY="54.8" pivotX="16" height="429" width="828" y="0" x="6441" name="ALT ARM DANCE UP0000"/>

<SubTexture height="429" width="828" y="0" x="6441" name="ALT ARM DANCE UP0001"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-23" frameX="-9" height="389" width="811" y="0" x="7269" name="ALT ARM DANCE UP0002"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-23" frameX="-9" height="389" width="811" y="0" x="7269" name="ALT ARM DANCE UP0003"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-28" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0004"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-28" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0005"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-35" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0006"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-35" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0007"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-35" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0008"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-35" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0009"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-35" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0010"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-35" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0011"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-35" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0012"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-35" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0013"/>

<SubTexture frameHeight="429" frameWidth="828" frameY="-35" frameX="-16" height="389" width="796" y="429" x="0" name="ALT ARM DANCE UP0014"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="-51" frameX="0" pivotY="120" pivotX="-76.4" height="549" width="730" y="429" x="796" name="ARM DANCE DOWN0000"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="-51" frameX="0" height="549" width="730" y="429" x="796" name="ARM DANCE DOWN0001"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="-29" frameX="-8" height="552" width="710" y="429" x="1526" name="ARM DANCE DOWN0002"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="-29" frameX="-8" height="552" width="710" y="429" x="1526" name="ARM DANCE DOWN0003"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="-4" frameX="-8" height="563" width="710" y="429" x="2236" name="ARM DANCE DOWN0004"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="-4" frameX="-8" height="563" width="710" y="429" x="2236" name="ARM DANCE DOWN0005"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="0" frameX="-8" height="698" width="710" y="429" x="2946" name="ARM DANCE DOWN0006"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="0" frameX="-8" height="698" width="710" y="429" x="2946" name="ARM DANCE DOWN0007"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="0" frameX="-8" height="698" width="710" y="429" x="2946" name="ARM DANCE DOWN0008"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="0" frameX="-8" height="698" width="710" y="429" x="2946" name="ARM DANCE DOWN0009"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="0" frameX="-8" height="698" width="710" y="429" x="2946" name="ARM DANCE DOWN0010"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="0" frameX="-8" height="698" width="710" y="429" x="2946" name="ARM DANCE DOWN0011"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="0" frameX="-8" height="698" width="710" y="429" x="2946" name="ARM DANCE DOWN0012"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="0" frameX="-8" height="698" width="710" y="429" x="2946" name="ARM DANCE DOWN0013"/>

<SubTexture frameHeight="698" frameWidth="730" frameY="0" frameX="-8" height="698" width="710" y="429" x="2946" name="ARM DANCE DOWN0014"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="-78" frameX="0" pivotY="0" pivotX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0000"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="-78" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0001"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="-44" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0002"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="-44" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0003"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="-26" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0004"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="-26" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0005"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="-16" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0006"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="-16" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0007"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="0" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0008"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="0" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0009"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="0" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0010"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="0" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0011"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="0" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0012"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="0" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0013"/>

<SubTexture frameHeight="434" frameWidth="796" frameY="0" frameX="0" height="356" width="796" y="429" x="3656" name="ARM DANCE IDLE0014"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="-65" frameX="-58" pivotY="260.7" pivotX="42.95" height="444" width="729" y="429" x="4452" name="ARM DANCE LEFT0000"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="-65" frameX="-58" height="444" width="729" y="429" x="4452" name="ARM DANCE LEFT0001"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="-34" frameX="-34" height="472" width="706" y="429" x="5181" name="ARM DANCE LEFT0002"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="-34" frameX="-34" height="472" width="706" y="429" x="5181" name="ARM DANCE LEFT0003"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="-16" frameX="-15" height="491" width="688" y="429" x="5887" name="ARM DANCE LEFT0004"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="-16" frameX="-15" height="491" width="688" y="429" x="5887" name="ARM DANCE LEFT0005"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="0" frameX="0" height="806" width="668" y="429" x="6575" name="ARM DANCE LEFT0006"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="0" frameX="0" height="806" width="668" y="429" x="6575" name="ARM DANCE LEFT0007"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="0" frameX="0" height="806" width="668" y="429" x="6575" name="ARM DANCE LEFT0008"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="0" frameX="0" height="806" width="668" y="429" x="6575" name="ARM DANCE LEFT0009"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="0" frameX="0" height="806" width="668" y="429" x="6575" name="ARM DANCE LEFT0010"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="0" frameX="0" height="806" width="668" y="429" x="6575" name="ARM DANCE LEFT0011"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="0" frameX="0" height="806" width="668" y="429" x="6575" name="ARM DANCE LEFT0012"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="0" frameX="0" height="806" width="668" y="429" x="6575" name="ARM DANCE LEFT0013"/>

<SubTexture frameHeight="806" frameWidth="787" frameY="0" frameX="0" height="806" width="668" y="429" x="6575" name="ARM DANCE LEFT0014"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="-48" frameX="0" pivotY="272" pivotX="-84.2" height="489" width="761" y="429" x="7243" name="ARM DANCE RIGHT 0000"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="-48" frameX="0" height="489" width="761" y="429" x="7243" name="ARM DANCE RIGHT 0001"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="-27" frameX="-21" height="506" width="750" y="1235" x="0" name="ARM DANCE RIGHT 0002"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="-27" frameX="-21" height="506" width="750" y="1235" x="0" name="ARM DANCE RIGHT 0003"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="-15" frameX="-34" height="516" width="743" y="1235" x="750" name="ARM DANCE RIGHT 0004"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="-15" frameX="-34" height="516" width="743" y="1235" x="750" name="ARM DANCE RIGHT 0005"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="0" frameX="-50" height="813" width="735" y="1235" x="1493" name="ARM DANCE RIGHT 0006"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="0" frameX="-50" height="813" width="735" y="1235" x="1493" name="ARM DANCE RIGHT 0007"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="0" frameX="-50" height="813" width="735" y="1235" x="1493" name="ARM DANCE RIGHT 0008"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="0" frameX="-50" height="813" width="735" y="1235" x="1493" name="ARM DANCE RIGHT 0009"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="0" frameX="-50" height="813" width="735" y="1235" x="1493" name="ARM DANCE RIGHT 0010"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="0" frameX="-50" height="813" width="735" y="1235" x="1493" name="ARM DANCE RIGHT 0011"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="0" frameX="-50" height="813" width="735" y="1235" x="1493" name="ARM DANCE RIGHT 0012"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="0" frameX="-50" height="813" width="735" y="1235" x="1493" name="ARM DANCE RIGHT 0013"/>

<SubTexture frameHeight="813" frameWidth="785" frameY="0" frameX="-50" height="813" width="735" y="1235" x="1493" name="ARM DANCE RIGHT 0014"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="-48" frameX="0" pivotY="149.1" pivotX="-66" height="671" width="681" y="1235" x="2228" name="ARM DANCE UP0000"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="-48" frameX="0" height="671" width="681" y="1235" x="2228" name="ARM DANCE UP0001"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="-23" frameX="-12" height="497" width="650" y="1235" x="2909" name="ARM DANCE UP0002"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="-23" frameX="-12" height="497" width="650" y="1235" x="2909" name="ARM DANCE UP0003"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="-6" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0004"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="-6" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0005"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="0" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0006"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="0" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0007"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="0" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0008"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="0" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0009"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="0" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0010"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="0" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0011"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="0" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0012"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="0" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0013"/>

<SubTexture frameHeight="719" frameWidth="681" frameY="0" frameX="-10" height="512" width="647" y="1235" x="3559" name="ARM DANCE UP0014"/>

<SubTexture frameHeight="1054" frameWidth="2572" frameY="0" frameX="0" pivotY="0" pivotX="0.35" height="996" width="2561" y="1235" x="4206" name="DEATH LOOP0000"/>

<SubTexture frameHeight="1054" frameWidth="2572" frameY="0" frameX="0" height="996" width="2561" y="1235" x="4206" name="DEATH LOOP0001"/>

<SubTexture frameHeight="1054" frameWidth="2572" frameY="-4" frameX="0" height="1012" width="2572" y="2231" x="0" name="DEATH LOOP0002"/>

<SubTexture frameHeight="1054" frameWidth="2572" frameY="-4" frameX="0" height="1012" width="2572" y="2231" x="0" name="DEATH LOOP0003"/>

<SubTexture frameHeight="1054" frameWidth="2572" frameY="-7" frameX="-18" height="1047" width="2546" y="2231" x="2572" name="DEATH LOOP0004"/>

<SubTexture frameHeight="1054" frameWidth="2572" frameY="-7" frameX="-18" height="1047" width="2546" y="2231" x="2572" name="DEATH LOOP0005"/>

<SubTexture frameHeight="1054" frameWidth="2572" frameY="-3" frameX="-6" height="1009" width="2565" y="2231" x="5118" name="DEATH LOOP0006"/>

<SubTexture frameHeight="1054" frameWidth="2572" frameY="-3" frameX="-6" height="1009" width="2565" y="2231" x="5118" name="DEATH LOOP0007"/>

<SubTexture frameHeight="947" frameWidth="2587" frameY="0" frameX="0" pivotY="0" pivotX="0" height="0" width="0" y="2231" x="7683" name="DIES0000"/>

<SubTexture frameHeight="947" frameWidth="2587" frameY="0" frameX="0" height="0" width="0" y="2231" x="7683" name="DIES0001"/>

<SubTexture height="947" width="2587" y="3278" x="0" name="DIES0002"/>

<SubTexture height="947" width="2587" y="3278" x="0" name="DIES0003"/>

<SubTexture height="947" width="2587" y="3278" x="2587" name="DIES0004"/>

<SubTexture height="947" width="2587" y="3278" x="2587" name="DIES0005"/>

<SubTexture height="947" width="2587" y="3278" x="5174" name="DIES0006"/>

<SubTexture height="947" width="2587" y="3278" x="5174" name="DIES0007"/>

<SubTexture height="947" width="2587" y="4225" x="0" name="DIES0008"/>

<SubTexture height="947" width="2587" y="4225" x="0" name="DIES0009"/>

<SubTexture height="947" width="2587" y="4225" x="2587" name="DIES0010"/>

<SubTexture height="947" width="2587" y="4225" x="2587" name="DIES0011"/>

<SubTexture height="947" width="2587" y="4225" x="2587" name="DIES0012"/>

<SubTexture height="947" width="2587" y="4225" x="2587" name="DIES0013"/>

<SubTexture height="947" width="2587" y="4225" x="2587" name="DIES0014"/>

<SubTexture pivotY="0" pivotX="0" height="692" width="611" y="4225" x="5174" name="REVIVE LMFAO0000"/>

<SubTexture height="692" width="611" y="4225" x="5174" name="REVIVE LMFAO0001"/>

<SubTexture height="692" width="611" y="4225" x="5174" name="REVIVE LMFAO0002"/>

<SubTexture height="692" width="611" y="4225" x="5174" name="REVIVE LMFAO0003"/>

<SubTexture height="692" width="611" y="4225" x="5785" name="REVIVE LMFAO0004"/>

<SubTexture height="692" width="611" y="4225" x="5785" name="REVIVE LMFAO0005"/>

<SubTexture frameHeight="692" frameWidth="611" frameY="0" frameX="0" height="0" width="0" y="4225" x="6396" name="REVIVE LMFAO0006"/>

<SubTexture frameHeight="692" frameWidth="611" frameY="0" frameX="0" height="0" width="0" y="4225" x="6396" name="REVIVE LMFAO0007"/>

<SubTexture frameHeight="692" frameWidth="611" frameY="0" frameX="0" height="0" width="0" y="4225" x="6396" name="REVIVE LMFAO0008"/>

<SubTexture frameHeight="692" frameWidth="611" frameY="0" frameX="0" height="0" width="0" y="4225" x="6396" name="REVIVE LMFAO0009"/>

<SubTexture frameHeight="692" frameWidth="611" frameY="0" frameX="0" height="0" width="0" y="4225" x="6396" name="REVIVE LMFAO0010"/>

<SubTexture frameHeight="692" frameWidth="611" frameY="0" frameX="0" height="0" width="0" y="4225" x="6396" name="REVIVE LMFAO0011"/>

</TextureAtlas>

**Comment by KyleOliverDeveloper** [comment]
nvm i cant send the xml

**Comment by frantastic24** [comment]
Change extension to .txt

**Comment by KyleOliverDeveloper** [comment]
> Change extension to .txt
[arm.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8082756/arm.txt)

**Comment by frantastic24** [comment]
it's working just fine here, only reset offsets because some death sprites are pushed out of bounds, but nothing outside of that
what version are you using?

https://user-images.githubusercontent.com/95725102/154342212-9e01f583-b4db-4e2a-98a7-c6043e87b3d5.mp4

**Comment by KyleOliverDeveloper** [comment]
> it's working just fine here, only reset offsets because some death sprites are pushed out of bounds, but nothing outside of that what version are you using?
> 
>  Friday.Night.Funkin._.Psych.Engine.2022-02-16.16-33-24.mp4

The newest version

**Comment by frantastic24** [comment]
still working fine in 0.5.1, so i'm doubting this is a bug

**Comment by KyleOliverDeveloper** [comment]
> still working fine in 0.5.1, so i'm doubting this is a bug

me too

**Comment by frantastic24** [comment]
just to make sure, are you running any game over scripts? all i used to change bf was:
```lua
function onCreate()
	setPropertyFromClass('GameOverSubstate', 'characterName', 'arm')
end
```
the only other cause i can think of is a pc issue

**Comment by KyleOliverDeveloper** [comment]
> just to make sure, are you running any game over scripts? all i used to change bf was:
> 
> ```lua
> function onCreate()
> 	setPropertyFromClass('GameOverSubstate', 'characterName', 'arm')
> end
> ```
> 
> the only other cause i can think of is a pc issue

yes i did use a gameover lua script

**Comment by KyleOliverDeveloper** [comment]
otherwise the death screen wouldnt load anything related to the character

**Comment by BombasticTom** [comment]
try reinstalling psych engine?
but before you do make sure to place your mods somewhere else out of the PsychEngine directory

**Comment by KyleOliverDeveloper** [comment]
> try reinstalling psych engine? but before you do make sure to place your mods somewhere else out of the PsychEngine directory

nop, doesnt work

**Comment by BombasticTom** [comment]
probably a pc issue then.
maybe show the code and tell us where did you place the script that plays the cutscene?

**Comment by KyleOliverDeveloper** [comment]
> probably a pc issue then. maybe show the code and tell us where did you place the script that plays the cutscene?

Remember when you told me to put the gameover script in mods/characters? so, i put it in there

**Comment by KyleOliverDeveloper** [comment]
> ok then it's a pc issue maybe

nop, my pc runs every other game over screen

**Comment by KyleOliverDeveloper** [comment]
so no it isnt

**Comment by frantastic24** [comment]
It renders correctly in my PC so clearly it's not a bug either
