### ISSUE TITLE
How to make modcharts compatible with a different number of keys other than 4?

### ISSUE THREAD

**Issue by supermase120** [ShadowMario/FNF-PsychEngine#8197]
### Describe your problem here.

For example, I wanna make a modchart where 9 keys spin around your screen like unfairness's modchart.

I got the 4 key modchart for unfairness, but instead of 4 keys, I wanna make it 8 keys.

Heres the problem, I'm a idiot and I don't know hot to do that.

I need help.

help me please.

Note: I'm using the extra keys mod made by tposejank

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by supermase120** [comment]
how*

**Comment by supermase120** [comment]
here is the code im using as my modchart

function onUpdate(elapsed)songPos = getSongPosition()

local currentBeat = (songPos/5000)*(curBpm/24)

noteTweenX(defaultPlayerStrumX0, 4, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + 0) * 300), 0.001)

noteTweenX(defaultPlayerStrumX1, 5, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + 1) * 300), 0.001)

noteTweenX(defaultPlayerStrumX2, 6, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + 2) * 300), 0.001)

noteTweenX(defaultPlayerStrumX3, 7, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + 3) * 300), 0.001)

noteTweenY('defaultPlayerStrumY0', 4, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + 0) * 300), 0.001)

noteTweenY('defaultPlayerStrumY1', 5, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + 1) * 300), 0.001)

noteTweenY('defaultPlayerStrumY2', 6, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + 2) * 300), 0.001)

noteTweenY('defaultPlayerStrumY3', 7, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + 3) * 300), 0.001)

noteTweenX('fake1', 0, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + (4) * 2) * 300), 0.001)

noteTweenX('fake2', 1, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + (5) * 2) * 300), 0.001)

noteTweenX('fake3', 2, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + (6) * 2) * 300), 0.001)

noteTweenX('fake4', 3, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + (7) * 2) * 300), 0.001)

noteTweenY('defaultFPlayerStrumY0', 0, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + (4) * 2) * 300), 0.001)

noteTweenY('defaultFPlayerStrumY1', 1, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + (5) * 2) * 300), 0.001)

noteTweenY('defaultFPlayerStrumY2', 2, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + (6) * 2) * 300), 0.001)

noteTweenY('defaultFPlayerStrumY3', 3, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + (7) * 2) * 300), 0.001)

end

**Comment by naether** [comment]
instead of using noteTween() use doTween() on the arrows's sprite or just setProperty

**Comment by supermase120** [comment]
> instead of using noteTween() use doTween() on the arrows's sprite or just setProperty

What if it's noteTweenX or noteTweenY

**Comment by supermase120** [comment]
> > instead of using noteTween() use doTween() on the arrows's sprite or just setProperty
> 
> What if it's noteTweenX or noteTweenY

Do I just add the X and Y or just delete it

**Comment by naether** [comment]
no just add doTweenX() and doTweenY()

**Comment by supermase120** [comment]
> no just add doTweenX() and doTweenY()

I edited the code and it doesn't work, no note moving

**Comment by naether** [comment]
you need to put the sprite you want to move in the function 💀
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers#dotweenxtagstring-varsstring-valuedynamic-durationfloat-easestring

**Comment by supermase120** [comment]
> you need to put the sprite you want to move in the function 💀 https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers#dotweenxtagstring-varsstring-valuedynamic-durationfloat-easestring

What the hell you mean by that? I'm a beginner coder and have never been confronted by this problem.

**Comment by naether** [comment]
can you tell me what happens when you try to use the 4k code in the 9k?
i don't really know how the extra keys mod works

**Comment by supermase120** [comment]
It's 8k actually, and the opponents side only works. Not BF's side.

**Comment by supermase120** [comment]
I think because of how the code only works with 4k. I just don't know how to fix it.

**Comment by naether** [comment]
try using this code

```
function onUpdate(elapsed
	songPos = getSongPosition()
	local currentBeat = (songPos/5000)*(curBpm/24)
	noteTweenX('defaultPlayerStrumX0', 4, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + 0) * 300), 0.001)
	noteTweenX('defaultPlayerStrumX1', 5, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + 1) * 300), 0.001)
	noteTweenX('defaultPlayerStrumX2', 6, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + 2) * 300), 0.001)
	noteTweenX('defaultPlayerStrumX3', 7, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + 3) * 300), 0.001)
	noteTweenX('defaultPlayerStrumX4', 8, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + 4) * 300), 0.001)
	noteTweenX('defaultPlayerStrumX5', 9, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + 5) * 300), 0.001)
	noteTweenX('defaultPlayerStrumX6', 10, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + 6) * 300), 0.001)
	noteTweenX('defaultPlayerStrumX7', 11, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + 7) * 300), 0.001)
	
	noteTweenY('defaultPlayerStrumY0', 4, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + 0) * 300), 0.001)
	noteTweenY('defaultPlayerStrumY1', 5, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + 1) * 300), 0.001)
	noteTweenY('defaultPlayerStrumY2', 6, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + 2) * 300), 0.001)
	noteTweenY('defaultPlayerStrumY3', 7, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + 3) * 300), 0.001)
	noteTweenY('defaultPlayerStrumY4', 8, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + 4) * 300), 0.001)
	noteTweenY('defaultPlayerStrumY5', 9, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + 5) * 300), 0.001)
	noteTweenY('defaultPlayerStrumY6', 10, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + 6) * 300), 0.001)
	noteTweenY('defaultPlayerStrumY7', 11, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + 7) * 300), 0.001)
	
	noteTweenX('fake1', 0, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + (4) * 2) * 300), 0.001)
	noteTweenX('fake2', 1, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + (5) * 2) * 300), 0.001)
	noteTweenX('fake3', 2, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + (6) * 2) * 300), 0.001)
	noteTweenX('fake4', 3, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + (7) * 2) * 300), 0.001)
	noteTweenX('fake5', 4, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + (8) * 2) * 300), 0.001)
	noteTweenX('fake6', 5, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + (9) * 2) * 300), 0.001)
	noteTweenX('fake7', 6, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + (10) * 2) * 300), 0.001)
	noteTweenX('fake8', 7, ((screenWidth / 2) - (157 / 2)) + (math.sin((currentBeat) + (11) * 2) * 300), 0.001)

	noteTweenY('defaultFPlayerStrumY0', 0, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + (4) * 2) * 300), 0.001)
	noteTweenY('defaultFPlayerStrumY1', 1, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + (5) * 2) * 300), 0.001)
	noteTweenY('defaultFPlayerStrumY2', 2, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + (6) * 2) * 300), 0.001)
	noteTweenY('defaultFPlayerStrumY3', 3, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + (7) * 2) * 300), 0.001)
	noteTweenY('defaultFPlayerStrumY4', 4, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + (8) * 2) * 300), 0.001)
	noteTweenY('defaultFPlayerStrumY5', 5, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + (9) * 2) * 300), 0.001)
	noteTweenY('defaultFPlayerStrumY6', 6, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + (10) * 2) * 300), 0.001)
	noteTweenY('defaultFPlayerStrumY7', 7, ((screenHeight / 2) - (157 / 2)) + (math.cos((currentBeat) + (11) * 2) * 300), 0.001)
end
```

**Comment by supermase120** [comment]
It worked, but 4 keys of bfs side aren't being moved

**Comment by naether** [comment]
try it again i think i fixed it

**Comment by supermase120** [comment]
Tried it again and it is still not working, 4 keys on bfs side aren't moving
